[package]
name = "pis"
version = "0.2.0"
edition = "2021"
authors = ["Vivek Naik <vivek.adishankara@gmail.com>"]
description = "A molecular dynamics simulator in Rust"

[lib]
name = "pis"
path = "src/lib.rs"

[features]
default = []
cli = ["dep:clap", "parallel"]
parallel = ["dep:rayon"]

[dependencies]
clap = { version = "4.5.47", features = ["derive"], optional = true }
nalgebra = "0.34.1"
parking_lot = "0.12.4"
rand = "0.10.0"
rand_distr = "0.6.0"
rayon = { version = "1.11.0", optional = true }
thiserror = "2.0.18"

[[bin]]
name = "pis"
path = "src/main.rs"
required-features = ["cli"]

[[bin]]
name = "sapphire"
path = "src/bin/sapphire/main.rs"

[dev-dependencies]
tempfile = "3.26.0"
rstest = "0.26.1"
